package main

import (
	"fmt"
	"strings"
)

// Response Autogenerated at https://mholt.github.io/json-to-go/
type Response struct {
	Date           string `json:"date"`
	Explanation    string `json:"explanation"`
	Hdurl          string `json:"hdurl"`
	MediaType      string `json:"media_type"`
	ServiceVersion string `json:"service_version"`
	Title          string `json:"title"`
	URL            string `json:"url"`
}

func main() {
	downloader := RealImageDownloader{}
	if err := run(downloader); err != nil {
		panic(err)
	}
}

func run(downloader ImageDownloader) error {
	result, err := FetchAPOD("https://api.nasa.gov/planetary/apod")
	if err != nil {
		return err
	}

	fmt.Println("Downloading image: " + result.Title)

	filename := result.Title + ".jpg"
	noSpaceFilename := strings.ReplaceAll(filename, " ", "_")

	return downloader.DownloadImage(result.Hdurl, "images", noSpaceFilename)
}
